'use strict';
// Dependency-free Chromium DevTools UI checks. No external services or packages.
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const { spawn } = require('node:child_process');
const W = require('../engine.js');
const root = path.resolve(__dirname, '..'), qa = path.join(root, 'qa');
const port = Number(process.env.QA_PORT || 4328);
const chrome = process.env.CHROME_PATH || path.join(process.env.LOCALAPPDATA || path.join(require('node:os').homedir(), 'AppData', 'Local'), 'ms-playwright', 'chromium_headless_shell-1228', 'chrome-headless-shell-win64', 'chrome-headless-shell.exe');
const profile = path.join(qa, 'browser-profile', `run-${Date.now()}`);
const delay = ms => new Promise(r => setTimeout(r, ms));
const reports = [], exceptions = [];
let browser, server, socket;
async function waitUntil(fn, description, ms = 10000) {
  const until = Date.now() + ms;
  do { if (await fn()) return; await delay(75); } while (Date.now() < until);
  throw new Error('Timed out: ' + description);
}
function pass(name) { reports.push(name); console.log('PASS ' + name); }
async function main() {
  fs.mkdirSync(profile, { recursive: true });
  server = spawn(process.execPath, ['server.cjs'], { cwd: root, env: { ...process.env, PORT: String(port) }, windowsHide: true, stdio: 'ignore' });
  await waitUntil(async () => { try { return (await fetch(`http://127.0.0.1:${port}`)).ok; } catch (e) { return false; } }, 'local server');
  const blocked = await fetch(`http://127.0.0.1:${port}/SPEC.md`); assert.equal(blocked.status, 404);
  const browserLog = fs.openSync(path.join(qa, 'chromium.log'), 'w');
  browser = spawn(chrome, ['--headless=new', '--no-sandbox', '--disable-gpu', '--no-first-run', '--no-default-browser-check', '--disable-background-networking', '--remote-debugging-port=0', '--remote-allow-origins=*', `--user-data-dir=${profile}`, 'about:blank'], { windowsHide: true, stdio: ['ignore', 'ignore', browserLog] });
  const activePort = path.join(profile, 'DevToolsActivePort');
  await waitUntil(() => fs.existsSync(activePort), 'Chromium debugging endpoint', 15000);
  const debugPort = fs.readFileSync(activePort, 'utf8').split('\n')[0];
  const targets = await (await fetch(`http://127.0.0.1:${debugPort}/json/list`)).json();
  socket = new WebSocket(targets.find(t => t.type === 'page').webSocketDebuggerUrl);
  await new Promise((resolve, reject) => { socket.addEventListener('open', resolve, { once: true }); socket.addEventListener('error', reject, { once: true }); });
  let seq = 0; const pending = new Map();
  socket.addEventListener('message', event => {
    const m = JSON.parse(event.data);
    if (m.id) { const p = pending.get(m.id); if (!p) return; pending.delete(m.id); clearTimeout(p.timer); m.error ? p.reject(new Error(JSON.stringify(m.error))) : p.resolve(m.result); }
    if (m.method === 'Runtime.exceptionThrown') exceptions.push(m.params.exceptionDetails.text + ' ' + JSON.stringify(m.params.exceptionDetails.exception));
  });
  const cdp = (method, params = {}) => new Promise((resolve, reject) => {
    const id = ++seq, timer = setTimeout(() => { pending.delete(id); reject(new Error('CDP timeout: ' + method)); }, 15000);
    pending.set(id, { resolve, reject, timer }); socket.send(JSON.stringify({ id, method, params }));
  });
  const evaluate = async expression => {
    const result = await cdp('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true });
    if (result.exceptionDetails) throw new Error(JSON.stringify(result.exceptionDetails));
    return result.result.value;
  };
  const ready = async () => { await delay(200); await waitUntil(() => evaluate('document.readyState === "complete" && !!window.Workshop && !!document.getElementById("app")?.children.length && document.querySelectorAll("[data-tab]").length >= 3'), 'game render'); };
  const snapshot = () => evaluate('JSON.parse(localStorage.getItem("birdsong-workshop-save-v1") || JSON.stringify({state: Workshop.initialState()})).state');
  const clickAction = async (type, properties = {}, twice = false) => {
    const found = await evaluate(`(() => { const el = [...document.querySelectorAll('[data-action]')].find(b => { const a = JSON.parse(b.dataset.action); return a.type === ${JSON.stringify(type)} && Object.entries(${JSON.stringify(properties)}).every(([k,v]) => a[k] === v); }); if (!el || el.disabled) return false; el.click(); ${twice ? 'el.click();' : ''} return true; })()`);
    assert(found, 'button available: ' + type + JSON.stringify(properties)); await delay(30);
  };
  const clickTab = async tab => { assert(await evaluate(`(() => { const el = document.querySelector('[data-tab="${tab}"]'); if(!el) return false; el.click(); return true; })()`), 'tab ' + tab); };
  const screenshot = async name => { const { data } = await cdp('Page.captureScreenshot', { format: 'png', captureBeyondViewport: true }); fs.writeFileSync(path.join(qa, name), Buffer.from(data, 'base64')); };
  await cdp('Page.enable'); await cdp('Runtime.enable');
  await cdp('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false });
  await cdp('Page.navigate', { url: `http://127.0.0.1:${port}` }); await ready();
  await evaluate('localStorage.clear(); location.reload()'); await ready();
  assert.equal(await evaluate('document.documentElement.lang'), 'zh-Hant');
  assert.equal(await evaluate('document.querySelectorAll("[data-tab]").length'), 3);
  assert(!await evaluate('document.body.innerText.includes("委託採購")'));
  await screenshot('01-first-screen-desktop.png');
  pass('首屏只顯示教學、兩個配方與基本功能；正體中文語言設定');
  await cdp('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
  assert(await evaluate('document.documentElement.scrollWidth <= window.innerWidth'), 'no mobile horizontal overflow');
  await screenshot('02-first-screen-mobile.png');
  await cdp('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false });
  pass('390px 窄螢幕無水平溢出，按鈕可操作');
  const pointer = await evaluate(`(() => { const el = [...document.querySelectorAll('[data-action]')].find(b => JSON.parse(b.dataset.action).recipe === 'staff'); el.scrollIntoView({block:'center'}); const r=el.getBoundingClientRect(); return {x:r.x+r.width/2,y:r.y+r.height/2}; })()`);
  await cdp('Input.dispatchMouseEvent', { type: 'mousePressed', button: 'left', clickCount: 1, ...pointer });
  await cdp('Input.dispatchMouseEvent', { type: 'mouseReleased', button: 'left', clickCount: 1, ...pointer });
  await evaluate(`(() => { const el = [...document.querySelectorAll('[data-action]')].find(b => JSON.parse(b.dataset.action).recipe === 'sword'); el.focus(); })()`);
  await cdp('Input.dispatchKeyEvent', { type: 'keyDown', key: 'Enter', code: 'Enter', windowsVirtualKeyCode: 13, text: '\r', unmodifiedText: '\r' });
  await cdp('Input.dispatchKeyEvent', { type: 'keyUp', key: 'Enter', code: 'Enter', windowsVirtualKeyCode: 13 });
  await delay(75);
  assert.equal(W.inventory(await snapshot()).length, 2, '滑鼠與 Enter 鍵各製作一件');
  assert.equal((await snapshot()).month, 0);
  assert(!await evaluate('document.querySelector("[data-action*=staff]") && !document.querySelector("[data-action*=staff]").disabled'));
  await clickAction('open', {}, true); let s = await snapshot(); assert.equal(s.month, 1); assert.equal(s.coins, 12);
  await clickAction('talk', {}, true); assert.equal((await snapshot()).npcs.cen.trust, 1);
  await clickAction('sell', { itemId: 'item-1' }, true); s = await snapshot(); assert.equal(s.items['item-1'].owner, 'cen'); assert.equal(s.tutorial.sold.length, 1);
  await clickAction('close'); const beforeReload = await snapshot(); await cdp('Page.reload'); await ready(); assert.deepEqual(await snapshot(), beforeReload);
  await clickAction('open'); assert.equal((await snapshot()).month, 2);
  assert(await evaluate('document.body.innerText.includes("還需要鐵劍")'));
  await clickAction('sell', { itemId: 'item-2' }); s = await snapshot(); assert.equal(s.tutorial.sold.length, 2); assert.equal(W.owned(s, 'cen').length, 2);
  pass('實際按鈕完成雙製作、雙擊開店去重、逐件售出；教學中關店與重載不丟失需求');
  await evaluate('document.getElementById("order-quantity").value="1.5"'); await clickAction('order-form');
  assert.equal((await snapshot()).orders.length, 0); assert(await evaluate('document.getElementById("notice").textContent.includes("整數")'));
  await evaluate('document.getElementById("order-quantity").value="1"'); await clickAction('order-form', {}, true);
  s = await snapshot(); assert.equal(s.orders.length, 1); assert.equal(s.orders[0].status, 'pending');
  await clickAction('close'); await clickAction('open'); s = await snapshot(); assert.equal(s.month, 3); assert.equal(s.orders[0].status, 'delivered'); assert.equal(s.materials.銅, 1);
  assert(s.news.some(n => n.id === 'use-item-1')); assert.equal(W.activeVisit(s).npc, 'he');
  await screenshot('03-new-demand-and-bird-mail.png');
  await clickTab('craft'); await clickAction('craft', { recipe: 'watering' });
  await clickTab('inventory'); await clickAction('appraise'); assert.equal((await snapshot()).xp.appraisal, 1);
  await clickAction('sell'); s = await snapshot(); assert.equal(s.items['item-4'].owner, 'he'); assert.equal(W.activeVisit(s).npc, 'cen');
  pass('介面拒絕小數採購；訂單只扣一次、下月只交一次；新顧客、製作、鑑定及交易完整');
  await clickTab('settings');
  await cdp('Browser.setDownloadBehavior', { behavior: 'allow', downloadPath: qa });
  await evaluate('document.querySelector("[data-tool=export]").click()');
  const download = path.join(qa, `鳥信工坊-第${s.month}月.json`);
  await waitUntil(() => fs.existsSync(download), 'exported backup');
  const exported = W.importSave(fs.readFileSync(download, 'utf8')); assert.deepEqual(exported, s);
  await evaluate('document.querySelector("[data-tool=new]").click()'); assert(await evaluate('document.getElementById("confirm-dialog").open'));
  await evaluate('document.getElementById("confirm-yes").click()'); await delay(50); assert.equal((await snapshot()).month, 0);
  await clickTab('settings');
  const doc = await cdp('DOM.getDocument'); const input = await cdp('DOM.querySelector', { nodeId: doc.root.nodeId, selector: '#import-file' });
  await cdp('DOM.setFileInputFiles', { nodeId: input.nodeId, files: [download] });
  await waitUntil(() => evaluate('document.getElementById("confirm-dialog").open'), 'import confirmation');
  await evaluate('document.getElementById("confirm-yes").click()'); await delay(50); assert.deepEqual(await snapshot(), s);
  const badFile = path.join(qa, 'invalid-save.json'); fs.writeFileSync(badFile, '{bad');
  await cdp('DOM.setFileInputFiles', { nodeId: input.nodeId, files: [badFile] }); await delay(75); assert.deepEqual(await snapshot(), s);
  assert(await evaluate('document.getElementById("notice").textContent.includes("匯入失敗")'));
  pass('真正下載 JSON、重新開始確認、檔案選擇匯入及壞檔拒絕；進度完整保留');
  await clickAction('close'); await clickAction('open'); s = await snapshot(); assert(s.returns.some(o => o.itemId === 'item-1'));
  await clickTab('mail'); await clickAction('reclaim', { itemId: 'item-1' }); assert.equal((await snapshot()).items['item-1'].status, 'inventory');
  await clickTab('inventory'); await clickAction('smelt', { itemId: 'item-1' });
  assert(await evaluate('document.getElementById("confirm-dialog").open'));
  await evaluate('document.getElementById("confirm-yes").click()'); await delay(50); assert.equal((await snapshot()).items['item-1'].status, 'smelted');
  await clickTab('craft'); await clickAction('craft', { recipe: 'staff' }); s = await snapshot();
  assert.equal(Object.values(s.items).at(-1).legacy, 'item-1'); await clickTab('collection');
  assert(await evaluate('document.body.innerText.includes("已熔鍊") && document.body.innerText.includes("承接 item-1")'));
  await evaluate('[...document.querySelectorAll("#panel details")].forEach(el => el.open=true)');
  await screenshot('04-legacy-collection.png');
  await cdp('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
  assert(await evaluate('document.documentElement.scrollWidth <= window.innerWidth'));
  await screenshot('05-collection-mobile.png');
  pass('合理贈還→實際熔鍊確認→材料傳承→收藏歷史；後期手機版無溢出');
  const saved = await snapshot(); await cdp('Page.reload'); await ready(); assert.deepEqual(await snapshot(), saved); W.validate(saved);
  await evaluate(`(() => { const key='birdsong-workshop-save-v1'; const next=Workshop.dispatch(JSON.parse(localStorage.getItem(key)).state,{type:'close'}).state; localStorage.setItem(key, Workshop.exportSave(next)); })()`);
  await clickAction('close');
  assert(await evaluate('document.getElementById("notice").textContent.includes("另一個視窗")'));
  assert.equal((await snapshot()).month, saved.month); assert.equal((await snapshot()).open, false);
  pass('另一視窗更新時，舊畫面操作會同步並拒絕重複結算');
  await evaluate(`(() => { const key='birdsong-workshop-save-v1'; localStorage.setItem(key+'-previous',localStorage.getItem(key)); localStorage.setItem(key,'{bad'); })()`);
  await cdp('Page.reload'); await ready();
  assert(await evaluate('document.getElementById("notice").textContent.includes("上一筆自動備份")'));
  await clickAction('open'); assert.equal((await snapshot()).month, saved.month + 1); W.validate(await snapshot());
  pass('主存檔損壞時會復原上一筆備份，下一次操作可正常再保存');
  assert.equal(exceptions.length, 0, 'no unhandled browser errors');
  pass('後期進度重載完全一致，沒有未處理的瀏覽器例外');
  const result = { status: 'passed', checks: reports, exceptions, month: (await snapshot()).month, browser: chrome, localOnly: true, screenshots: fs.readdirSync(qa).filter(n => n.endsWith('.png')), finishedAt: new Date().toISOString() };
  fs.writeFileSync(path.join(qa, 'browser-report.json'), JSON.stringify(result, null, 2));
}
main().catch(error => { console.error(error); fs.mkdirSync(qa, { recursive: true }); fs.writeFileSync(path.join(qa, 'browser-report.json'), JSON.stringify({ status: 'failed', checks: reports, exceptions, error: error.stack }, null, 2)); process.exitCode = 1; }).finally(async () => {
  if (socket) socket.close(); if (browser) browser.kill(); if (server) server.kill();
});
