'use strict';
const {test}=require('node:test'), assert=require('node:assert/strict'), W=require('../engine.js');
const {game,craft,intro,order,explore,ready,next,depart,at,returnedStaff}=require('./helpers.cjs');
const scope=(g,a)=>({visitId:W.activeVisit(g.s)?.id,counterId:W.activeVisit(g.s)?.counterId,...a});
function reject(g,a,re){const before=W.exportSave(g.s);assert.throws(()=>g.do(a),re);assert.equal(W.exportSave(g.s),before);}
function accept(g,id='customer'){g.npc({type:'accept-commission',requestId:id});return g.s.commissions.at(-1);}
function customer(){const g=ready();g.npc({type:'talk'});return {g,c:accept(g)};}
function request(g,npc,recipe,extra={}){while(W.activeVisit(g.s))depart(g);const id=`focus-${g.s.month}-${g.s.seq}`;g.s.visits.push({id,month:g.s.month,npc,needs:[recipe],kind:'normal',asked:true,status:'waiting',phase:'request',counterId:`${id}@${g.s.month}`,reason:'指定用途',minQuality:0,traitRequired:null,contentKey:null,contextText:'',...extra});W.validate(g.s);}
test('起始木鐵各三；開始扣料、零月不完工、不加經驗',()=>{const g=game(),a=craft(g,'staff'),b=craft(g,'sword');assert.equal(g.s.materials.木頭,2);assert.equal(g.s.materials.鐵,2);assert.equal(g.s.month,0);assert.equal(g.s.xp.craft,0);assert.equal(W.inventory(g.s).length,0);assert.equal(a.status,'crafting');assert.equal(a.dueMonth,1);assert.equal(b.dueMonth,1);assert.deepEqual(W.knownMaterials(g.s),['木頭','鐵']);});
test('六件並行無產能限制，缺料原子拒絕，下次開店全完工',()=>{const g=game();for(let n=0;n<3;n++){craft(g,'staff');craft(g,'sword');}reject(g,{type:'craft',recipe:'staff'},/需要/);reject(g,{type:'craft',recipe:'bell'},/尚未/);next(g);assert.equal(W.inventory(g.s).length,6);assert.equal(g.s.xp.craft,6);assert(Object.values(g.s.items).every(i=>i.finishedMonth===1&&i.durability===9));});
test('首次月一只扣一次，雙擊開店、重複關店不重複結算',()=>{const g=game();next(g);assert.equal(g.s.month,1);assert.equal(g.s.coins,12);reject(g,{type:'open'},/已經營業/);const news=JSON.stringify(g.s.news);g.do({type:'close'});assert.equal(g.s.coins,12);assert.equal(g.s.month,1);assert.equal(JSON.stringify(g.s.news),news);reject(g,{type:'close'},/已經關店/);});
test('營業與關店可開始；唯開店換月完成，重載不推進',()=>{const g=game();next(g);const a=craft(g,'staff');g.do({type:'close'});const b=craft(g,'sword');g.s=W.importSave(W.exportSave(g.s));assert.equal(g.s.items[a.id].status,'crafting');assert.equal(g.s.items[b.id].status,'crafting');next(g);assert.equal(W.inventory(g.s).length,2);assert.equal(g.s.xp.craft,2);});
test('自然教學兩件→同一買家→探索→下月新需求與配方',()=>{const g=game();intro(g);assert.equal(W.owned(g.s,'cen').length,2);assert.equal(W.tutorialStep(g.s).step,3);assert.equal(g.s.npcs.cen.story,false);explore(g);assert.equal(W.tutorialStep(g.s).step,4);next(g);assert.equal(g.s.materials.銅,2);assert.equal(W.activeVisit(g.s).npc,'he');assert.deepEqual(W.visibleRecipes(g.s),['staff','sword']);g.npc({type:'talk'});assert.deepEqual(W.visibleRecipes(g.s),['staff','sword','bracer']);assert(W.canAppraise(g.s));});
test('提早開關、售一件中斷、未採購重載均可續接教學',()=>{const g=game();next(g);g.do({type:'close'});const a=craft(g,'staff'),b=craft(g,'sword');next(g);g.npc({type:'sell',itemId:a.id});const stale=scope(g,{type:'talk'});g.do({type:'close'});g.s=W.importSave(W.exportSave(g.s));next(g);reject(g,stale,/不在櫃臺/);assert.deepEqual(W.activeVisit(g.s).needs,['sword']);g.npc({type:'sell',itemId:b.id});next(g);assert.equal(W.activeVisit(g.s).phase,'service');explore(g);next(g);assert.equal(g.s.materials.銅,2);assert.equal(g.s.visits.filter(v=>v.kind==='intro').length,1);});
test('先採購木頭也推進教學，小禾先提供探索而不泄露配方',()=>{const g=game();intro(g);order(g,'木頭',2);next(g);assert(g.s.tutorial.delivered);assert.equal(W.activeVisit(g.s).npc,'he');assert.deepEqual(W.activeVisit(g.s).needs,[]);assert(!W.unlocked(g.s,'bracer'));explore(g);next(g);assert.equal(g.s.materials.銅,2);});
test('逐人接客：下一人、送客、關店、跨月舊 token 拒絕',()=>{const g=ready(),other=g.s.visits.find(v=>v.status==='waiting'&&v.npc!=='he');reject(g,{type:'talk',visitId:other.id,counterId:other.counterId},/不在櫃臺/);const a=scope(g,{type:'talk'});depart(g);reject(g,a,/不在櫃臺/);const b=scope(g,{type:'talk'});g.do({type:'close'});reject(g,b,/不在櫃臺/);next(g);reject(g,b,/不在櫃臺/);});
test('重複對話、重售物品、過期 revision 不改狀態',()=>{const g=game();intro(g);reject(g,scope(g,{type:'talk'}),/已經聽/);reject(g,scope(g,{type:'sell',itemId:'item-1'}),/不在工坊/);reject(g,{type:'close',expectedRevision:g.s.revision-1},/已處理/);});
test('採購一萬即記帳、request 去重，下月只交付一次',()=>{const g=game();intro(g);const money=g.s.coins;order(g,'木頭',10000,'one');assert.equal(g.s.debt,30000-money);reject(g,scope(g,{type:'order',material:'木頭',quantity:10000,requestId:'one'}),/已接受/);g.npc({type:'leave'});next(g);assert.equal(g.s.materials.木頭,10002);next(g);assert.equal(g.s.materials.木頭,10002);assert.equal(g.s.news.filter(n=>n.id==='delivery-order-3').length,1);});
test('採購非法數量、未知材料、安全整數與總價溢位原子拒絕',()=>{const g=game();intro(g);for(const quantity of [NaN,Infinity,-1,0,1.1,'1',Number.MAX_SAFE_INTEGER+1])reject(g,scope(g,{type:'order',material:'木頭',quantity,requestId:'bad'}),/安全整數/);reject(g,scope(g,{type:'order',material:'木頭',quantity:Number.MAX_SAFE_INTEGER,requestId:'overflow'}),/安全整數/);reject(g,scope(g,{type:'order',material:'銅',quantity:1,requestId:'unknown'}),/已辨識/);g.s.coins=0;g.s.debt=Number.MAX_SAFE_INTEGER;reject(g,scope(g,{type:'order',material:'木頭',quantity:1,requestId:'debt'}),/安全整數/);g.s.debt=0;g.s.materials.木頭=Number.MAX_SAFE_INTEGER;reject(g,scope(g,{type:'order',material:'木頭',quantity:1,requestId:'material'}),/安全整數/);});
test('人物採購／探索共用單一任務，跨種類 request ID 去重',()=>{const g=game();intro(g);order(g,'鐵',2,'same');reject(g,scope(g,{type:'explore',requestId:'same'}),/已接受/);reject(g,scope(g,{type:'explore',requestId:'new'}),/未完成委託/);reject(g,scope(g,{type:'order',material:'木頭',quantity:1,requestId:'new'}),/未完成委託/);next(g);assert.equal(W.pendingTasks(g.s,'cen').length,0);});
test('探索六枚，銅→銀→金一次交付各二；未知不能先解鎖',()=>{const g=game();intro(g);const money=g.s.coins;explore(g,'one');assert.equal(g.s.coins,money-6);assert(!W.unlocked(g.s,'bracer'));next(g);assert.equal(W.nextUnknown(g.s),'銀');explore(g,'two');next(g);assert.equal(W.nextUnknown(g.s),'金');explore(g,'three');next(g);assert.equal(W.nextUnknown(g.s),null);assert.deepEqual(W.knownMaterials(g.s),W.MATERIALS);for(const m of ['銅','銀','金'])assert.equal(g.s.materials[m],2);reject(g,scope(g,{type:'explore',requestId:'four'}),/都已辨識/);});
test('同一探索線索不能跨人並行，其他採購可辦',()=>{const g=ready();explore(g);depart(g);reject(g,scope(g,{type:'explore',requestId:'other'}),/已有人探索/);order(g,'木頭',1);assert.equal(g.s.orders.length,1);});
test('客人委託開工不售出、付款、使用，同人不能另採購／探索',()=>{const {g,c}=customer(),i=g.s.items[c.itemId];assert.equal(c.status,'crafting');assert.equal(i.owner,null);assert.equal(i.soldMonth,null);assert.equal(i.episodes.length,0);assert.equal(g.s.reputation,2);reject(g,scope(g,{type:'order',material:'銅',quantity:1,requestId:'busy'}),/未完成委託/);reject(g,scope(g,{type:'explore',requestId:'busy2'}),/未完成委託/);reject(g,scope(g,{type:'sell',itemId:i.id}),/不在工坊/);assert(!g.s.content.events.some(e=>e.key==='he-wrist'));});
test('完工保留指定成品，當面交貨才付款與轉移；交貨去重',()=>{const {g,c}=customer();next(g);at(g,'he');const i=g.s.items[c.itemId],money=g.s.coins;assert.equal(i.status,'inventory');assert.equal(g.s.commissions[0].status,'ready');assert.equal(W.activeVisit(g.s).kind,'delivery');reject(g,scope(g,{type:'sell',itemId:i.id}),/交付按鈕/);g.npc({type:'deliver',itemId:i.id});assert.equal(g.s.items[i.id].owner,'he');assert.equal(g.s.items[i.id].reservedFor,null);assert.equal(g.s.coins,money+W.price(i));assert.equal(g.s.items[i.id].episodes[0].uses,0);reject(g,scope(g,{type:'deliver',itemId:i.id}),/不是目前/);assert.equal(W.pendingTasks(g.s,'he').length,0);order(g,'銅',5);next(g);assert.equal(g.s.items[i.id].episodes[0].uses,1);});
test('預留成品不可跨人出售，婉拒領貨下月仍可來，不提前使用',()=>{const {g,c}=customer();next(g);at(g,'he');const i=g.s.items[c.itemId];g.npc({type:'decline'});const other={...W.activeVisit(g.s),phase:'request',needs:['bracer'],minQuality:0};assert.match(W.recommendationReason(g.s,i,other),/委託成品/);next(g);at(g,'he');assert.equal(W.activeVisit(g.s).kind,'delivery');assert.equal(g.s.items[i.id].episodes.length,0);assert.equal(g.s.items[i.id].durability,9);g.npc({type:'deliver',itemId:i.id});next(g);assert.equal(g.s.items[i.id].episodes[0].firstUsedMonth,g.s.month);});
test('缺材料委託待開工，本人在場可取消後採購，避免軟鎖',()=>{const g=ready();g.s.materials.銅=0;const c=accept(g);assert.equal(c.status,'accepted');reject(g,scope(g,{type:'order',material:'銅',quantity:1,requestId:'busy'}),/未完成委託/);g.do({type:'close'});reject(g,{type:'cancel-commission',commissionId:c.id},/不在櫃臺/);next(g);at(g,'he');g.npc({type:'cancel-commission',commissionId:c.id});order(g,'銅',1);next(g);assert.equal(g.s.materials.銅,1);});
test('品質不足待開工；練習完工後關店也能開始指定委託',()=>{const g=ready();request(g,'cen','staff',{minQuality:1});const c=accept(g);assert.equal(c.status,'accepted');reject(g,{type:'craft',commissionId:c.id},/未達/);craft(g,'sword');next(g);assert.equal(g.s.xp.craft,3);g.do({type:'close'});g.do({type:'craft',commissionId:c.id});assert.equal(g.s.commissions[0].status,'crafting');assert.equal(g.s.items[g.s.commissions[0].itemId].quality,1);reject(g,{type:'craft',commissionId:c.id},/已開始/);});
test('合用現貨存在時直接售出，不另接製作委託',()=>{const g=ready();craft(g,'bracer');next(g);at(g,'he');reject(g,scope(g,{type:'accept-commission',requestId:'stock'}),/合適現貨/);const i=W.inventory(g.s).find(i=>i.recipe==='bracer');g.npc({type:'sell',itemId:i.id});assert.equal(g.s.items[i.id].owner,'he');});
test('複雜金鈴兩個月，重載保留工期，加價只實際交貨一次',()=>{const g=ready();explore(g);next(g);explore(g);next(g);g.s.xp.craft=6;g.s.reputation=5;request(g,'shu','bell',{kind:'commission'});const c=accept(g);assert.equal(g.s.items[c.itemId].dueMonth,g.s.month+2);next(g);assert.equal(g.s.items[c.itemId].status,'crafting');g.s=W.importSave(W.exportSave(g.s));next(g);at(g,'shu');const net=g.s.coins-g.s.debt;g.npc({type:'deliver',itemId:c.itemId});assert.equal(g.s.coins-g.s.debt,net+38);assert.equal(g.s.npcs.shu.goldDone,true);});
test('鑑定僅完工實物一次；製作與重載不磨耗，使用才磨耗',()=>{const g=ready();g.npc({type:'talk'});const i=craft(g,'bracer');reject(g,{type:'appraise',itemId:i.id},/實物/);g.do({type:'close'});g.s=W.importSave(W.exportSave(g.s));assert.equal(g.s.items['item-1'].durability,6);next(g);assert.equal(g.s.items['item-1'].durability,3);g.do({type:'appraise',itemId:i.id});assert.equal(g.s.month,3);assert.equal(g.s.xp.appraisal,1);reject(g,{type:'appraise',itemId:i.id},/已鑑定/);});
test('故事綁真實使用，僅多次談話不虛構使用故事',()=>{const g=ready();assert.equal(g.s.npcs.cen.story,false);next(g);assert(g.s.npcs.cen.story);assert(g.s.items[g.s.npcs.cen.storyItem].episodes.some(e=>e.npc==='cen'&&e.firstUsedMonth<g.s.month));for(let n=0;n<8;n++){while(W.activeVisit(g.s)){if(W.activeVisit(g.s).npc==='he'&&!W.activeVisit(g.s).asked)g.npc({type:'talk'});depart(g);}next(g);}assert(g.s.npcs.he.trust>=3);assert.equal(g.s.npcs.he.story,false);});
test('磨損實物當面贈還，修復一次可跨主再售，原退役者不回買',()=>{const {g,item}=returnedStaff();assert.equal(item.status,'inventory');assert.equal(item.episodes[0].until,3);reject(g,scope(g,{type:'reclaim',itemId:item.id}),/只能當面/);const other={...W.activeVisit(g.s),phase:'request',needs:['staff'],npc:'shu',minQuality:0};assert.match(W.recommendationReason(g.s,item,other),/修復/);g.do({type:'repair',itemId:item.id});const repaired=g.s.items[item.id];assert(W.suitable(g.s,repaired,other));assert.match(W.recommendationReason(g.s,repaired,{...other,npc:'cen'}),/不再買回/);reject(g,{type:'repair',itemId:item.id},/尚未修復/);request(g,'shu','staff');g.npc({type:'sell',itemId:item.id});next(g);assert.equal(g.s.items[item.id].episodes.length,2);assert.equal(g.s.items[item.id].episodes[1].uses,1);});
test('熔鍊消耗防重複，材料與特性僅傳承一次',()=>{const {g,item}=returnedStaff(),amount=g.s.materials.木頭;g.do({type:'smelt',itemId:item.id});assert.equal(g.s.materials.木頭,amount+1);reject(g,{type:'smelt',itemId:item.id},/舊物/);const fresh=craft(g,'shield');assert.equal(fresh.legacy,item.id);assert.deepEqual(fresh.traits,['solid','light']);assert.equal(g.s.legacies[0].usedBy,fresh.id);assert.equal(craft(g,'staff').legacy,null);next(g);assert.equal(g.s.items[item.id].status,'smelted');});
test('品質售價、護身結果與堅固磨耗；欠款不中止採購交貨',()=>{for(let q=0;q<3;q++)for(const recipe of Object.keys(W.RECIPES))assert.equal(W.price({recipe,quality:q}),W.QUALITY_PRICE[q]);const i={recipe:'shield',quality:0,traits:['solid'],durability:9},b={...i,traits:['solid','guard']};assert(!W.useResult(i).strong);assert(W.useResult(b).strong);assert(W.useResult(b).wear<W.useResult(i).wear);const g=ready();g.s.coins=0;g.s.debt=500;order(g,'銅',100);next(g);at(g,'he');const c=accept(g);next(g);at(g,'he');const debt=g.s.debt;g.npc({type:'deliver',itemId:c.itemId});assert.equal(g.s.coins,0);assert(g.s.debt<debt);});
for(const version of [1,2,3])test(`真實 schema ${version} 遷移保留進度與舊成品，不回收重製`,()=>{const Old=require(`./fixtures/engine-v${version}.cjs`);let s=Old.initialState();s=Old.dispatch(s,{type:'craft',recipe:'staff'}).state;s=Old.dispatch(s,{type:'open'}).state;const current=W.importSave(Old.exportSave(s));assert.equal(current.schema,4);assert.equal(current.month,s.month);assert.equal(current.coins,s.coins);assert.equal(current.items['item-1'].status,'inventory');assert.equal(current.items['item-1'].dueMonth,null);assert.deepEqual(current.knownMaterials,W.MATERIALS);assert.deepEqual(W.importSave(W.exportSave(current)),current);});
test('舊版同人多張採購保留，全部交付後才接新任務',()=>{const Old=require('./fixtures/engine-v3.cjs');let s=Old.initialState();const act=a=>s=Old.dispatch(s,a).state;act({type:'craft',recipe:'staff'});act({type:'craft',recipe:'sword'});act({type:'open'});for(const itemId of ['item-1','item-2']){const v=Old.activeVisit(s);act({type:'sell',itemId,visitId:v.id,counterId:v.counterId});}for(const [n,material]of ['木頭','銅','金'].entries()){const v=Old.activeVisit(s);act({type:'order',material,quantity:12,requestId:`old-${n}`,visitId:v.id,counterId:v.counterId});}const g=game();g.s=W.importSave(Old.exportSave(s));assert.equal(g.s.legacyTaskIds.length,3);reject(g,scope(g,{type:'order',material:'鐵',quantity:1,requestId:'new'}),/未完成委託/);next(g);assert.equal(g.s.legacyTaskIds.length,0);assert.equal(g.s.materials.金,12);assert(g.s.orders.every(o=>o.status==='delivered'));});
test('schema4 完整往返；偽造工期、知識、委託、所有權拒絕',()=>{const {g,c}=customer(),text=W.exportSave(g.s);assert.deepEqual(W.importSave(text),g.s);for(const mutate of [s=>s.items[c.itemId].dueMonth=s.month,s=>s.items[c.itemId].reservedFor='bad',s=>s.knownMaterials=['木頭','鐵','銀'],s=>s.commissions.push(s.commissions[0]),s=>s.materials.木頭=-1,s=>s.items[c.itemId].owner='shu']){const d=JSON.parse(text);mutate(d.state);assert.throws(()=>W.importSave(JSON.stringify(d)),/存檔/);}assert.throws(()=>W.importSave('{bad'));assert.throws(()=>W.importSave(' '.repeat(8*1024*1024+1)),/太大/);});
module.exports={customer,request};
