'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {view}=require('./ui-harness.cjs'),W=require('../engine.js'),S=require('../lab-scenarios.js');
const choose=(v,key,props)=>v.clickEvent(v.buttons().find(b=>b.dataset.scene===key),props||{});

test('裝備整理六配方仍在緊湊選擇器，切換不推月／扣料且所有工期可真正製作',async()=>{
 const v=view({lab:true,autoReview:false});await choose(v,'equipment');const select=v.html().match(/<select id="lab-recipe">([\s\S]*?)<\/select>/);assert(select);assert.equal((select[1].match(/<option /g)||[]).length,6);assert.equal(v.buttons().filter(b=>b.action?.type==='craft').length,1);
 const before=JSON.stringify(v.state());await v.change('lab-recipe','bell');assert.equal(JSON.stringify(v.state()),before);assert.match(v.html(),/金鈴/);assert.match(v.html(),/金 1・2 個月/);await v.clickAction('craft',{recipe:'bell'});assert.equal(Object.values(v.state().items).at(-1).dueMonth,v.state().month+2);await v.change('lab-recipe','amulet');await v.clickAction('craft',{recipe:'amulet'});assert.match(v.html(),/第 .* 月開店完工/);
 const css=fs.readFileSync(path.join(__dirname,'../lab.css'),'utf8');assert.match(css,/#lab-app\[data-mode="forge"\]/);assert.match(css,/\.lab-forge[^}]*min-height:0/);assert.match(css,/\.lab-forge \.lab-list[^}]*overflow:auto/);assert.match(css,/\.lab-section p\{font-size:16px/);assert.match(css,/\.lab-card h3\{font-size:18px/);
});
test('裝備整理預設兩件真退役樣本，其他庫存折疊保留，熔鍊與新作可單獨辨識',async()=>{
 const v=view({lab:true,autoReview:false});await choose(v,'equipment');const match=v.html().match(/<details class="lab-other-items"><summary>其他庫存（(\d+) 件）<\/summary>([\s\S]*?)<\/details>/);assert(match);assert.equal(Number(match[1]),W.inventory(S.equipment.state).length-2);assert.equal((v.html().slice(0,v.html().indexOf('<details class="lab-other-items">')).match(/<article class="lab-card"/g)||[]).length,2);assert(!match[0].includes('<details class="lab-other-items" open'));
 const beforeItems=Object.keys(v.state().items).length,repair=v.buttons().find(b=>b.action?.type==='repair'&&!b.disabled),id=repair.action.itemId;await v.click(repair);assert(v.state().items[id].repaired);await v.clickAction('smelt',{itemId:id});assert.equal(v.state().items[id].status,'smelted');assert.equal(Object.keys(v.state().items).length,beforeItems);await v.change('lab-recipe','bracer');await v.clickAction('craft',{recipe:'bracer'});const item=Object.values(v.state().items).at(-1);assert(item.legacy);await v.clickAction('open');assert.equal(v.state().items[item.id].status,'inventory');assert.match(v.html(),/此次新作/);assert.match(v.html(),new RegExp(item.id));
});
test('交易、材料和營運導言明示起始情境，實際狀態更新而初始資料不冒充現在',async()=>{
 const v=view({lab:true,autoReview:false});for(const key of ['trade','materials','operations']){if(v.lab.key)await v.clickTool('menu');await choose(v,key);assert.match(v.html(),/<p class="lab-intro"><strong>起始情境：<\/strong>/);if(key==='trade'){await v.clickAction('deliver');await v.clickAction('leave');assert.equal(W.activeVisit(v.state()).npc,'cen');}else if(key==='materials'){await v.clickAction('explore');assert.match(v.html(),/已有背景任務/);}else{await v.clickAction('open');assert.equal(v.state().debt,4);assert.match(v.html(),/新欠款 4 枚/);}assert.match(v.html(),/<p class="lab-intro"><strong>起始情境：<\/strong>/);}
});
test('開店後立刻選擇測試和換人物不吞點擊，原情境獨立保留',async()=>{
 const v=view({lab:true,autoReview:false,now:()=>10});await choose(v,'operations',{detail:1});await v.clickEvent(v.button('open'),{detail:1});const month=v.state().month;assert.equal(await v.clickEvent(v.buttons().find(b=>b.dataset.tool==='menu'),{detail:1}),false);assert.equal(v.lab.key,null);await choose(v,'growth-cen',{detail:1});await v.clickEvent(v.button('open'),{detail:1});assert(W.characterProgress(v.state(),'cen').completed);assert.equal(await choose(v,'growth-shu',{detail:1}),false);assert.equal(v.lab.key,'growth-shu');assert(!W.characterProgress(v.state(),'shu').completed);await v.clickTool('menu');await choose(v,'operations',{detail:1});assert.equal(v.state().month,month);
});
test('月結後立刻換模式和重置可用，同段快速結算點擊仍攔截',async()=>{
 let now=10;const v=view({lab:true,autoReview:false,now:()=>now});await choose(v,'operations',{detail:1});await v.clickEvent(v.button('open'),{detail:1});const before=JSON.stringify(v.state());assert.equal(await v.clickEvent(v.button('review-next'),{detail:1}),true);assert.equal(JSON.stringify(v.state()),before);now=700;await v.clickEvent(v.button('review-next'),{detail:1});const cursor=v.state().monthReview.cursor;await v.clickEvent(v.buttons().find(b=>b.dataset.tool==='menu'),{detail:1});assert.equal(v.lab.key,null);await choose(v,'operations',{detail:1});assert.equal(v.state().monthReview.cursor,cursor);await v.clickEvent(v.buttons().find(b=>b.dataset.tool==='reset'),{detail:1});assert.equal(v.state().month,S.operations.state.month);assert.equal(v.state().debt,0);await v.clickEvent(v.button('open'),{detail:1});assert.equal(v.state().debt,4);assert.equal(v.state().month,S.operations.state.month+1);
});
