'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {view}=require('./ui-harness.cjs');
async function free(){const v=view({lab:true,autoReview:false,trialRandom:()=>0});await v.click(v.buttons().find(b=>b.dataset.scene==='forge'));await v.clickTool('forge-trial');return v;}
const reuse=v=>v.click(v.buttons().find(b=>b.dataset.trial==='reuse'));
const start=v=>v.click(v.buttons().find(b=>b.dataset.trial==='start'));
test('配料簿選取及套用保留展開和焦點，重繪／切模式不重抽，手動收起及重置仍可',async()=>{
 const v=await free();v.element('trial-book-panel').open=true;const before=JSON.stringify(v.trial.state);await v.change('trial-book','0,0,0,1,0');assert.match(v.html(),/<details class="trial-book" id="trial-book-panel" open>/);assert(v.element('trial-book-panel').open);assert.match(v.html(),/class="trial-book-actions"><select id="trial-book"/);assert(v.element('trial-book').focused);await reuse(v);assert(v.element('trial-book-panel').open);assert(v.element('trial-reuse').focused);assert.equal(v.element('trial-q-3').value,'1');assert.equal(JSON.stringify(v.trial.state),before);await start(v);const item=v.trial.state.items[0],traits=Array.from(item.traits);assert(v.element('trial-book-panel').open);await v.clickAction('open');assert(v.element('trial-book-panel').open);assert.equal(v.trial.state.items[0].status,'crafting');await v.clickTool('forge-fixed');await v.clickTool('forge-trial');assert(v.element('trial-book-panel').open);assert.deepEqual(Array.from(v.trial.state.items[0].traits),traits);v.element('trial-book-panel').open=false;await v.change('trial-book','1,0,0,0,0');assert(!v.element('trial-book-panel').open);await v.clickTool('reset');await v.clickTool('forge-trial');assert(!v.element('trial-book-panel').open);assert.equal(v.trial.state.items.length,0);
});
test('空排程是短行，長排程緊湊內捲；四件對照為單列資料而不縮字',async()=>{
 const v=await free();assert.match(v.html(),/lab-trial-board empty-trial-queue/);assert.match(v.html(),/目前沒有在製品/);for(const n of [1,2,3,4]){v.element('trial-q-0').value=String(n);await start(v);}assert.match(v.html(),/lab-trial-board has-trial-queue/);assert.equal((v.html().match(/class="trial-queue-entry"/g)||[]).length,4);await v.clickAction('open');assert.match(v.html(),/lab-trial-board empty-trial-queue/);const table=v.html().match(/<table class="trial-results">([\s\S]*?)<\/table>/)[1];assert.equal((table.match(/<tr>/g)||[]).length,5);assert(!table.includes('<br>'));assert.match(table,/耐久／磨耗/);assert.match(table,/9／9 · 3/);assert.match(table,/12／12 · 3/);const css=fs.readFileSync(path.join(__dirname,'../lab.css'),'utf8');assert.match(css,/\.lab-trial-board\.empty-trial-queue\{grid-template-rows:auto minmax\(0,1fr\)/);assert.match(css,/\.lab-trial-board\.has-trial-queue\{grid-template-rows:minmax\(0,140px\) minmax\(0,1fr\)/);assert.match(css,/\.trial-results\{[^}]*font-size:16px/);assert.match(css,/\.trial-queue-entry[^}]*font-size:16px/);
});
