'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {view}=require('./ui-harness.cjs');
async function free(){const v=view({lab:true,autoReview:false,trialRandom:()=>0});await v.click(v.buttons().find(b=>b.dataset.scene==='forge'));return v;}
const reuse=v=>v.click(v.buttons().find(b=>b.dataset.trial==='reuse'));
const start=v=>v.click(v.buttons().find(b=>b.dataset.trial==='forge'));
test('配料簿選取及套用保留展開和焦點，重繪／切模式不重抽，手動收起及重置仍可',async()=>{
 const v=await free();v.element('trial-book-panel').open=true;const before=JSON.stringify(v.trial.state);await v.change('trial-book','0,2,0,0,0');assert.match(v.html(),/<details class="trial-book" id="trial-book-panel" open>/);assert(v.element('trial-book-panel').open);assert.match(v.html(),/class="trial-book-actions"><select id="trial-book"/);assert(v.element('trial-book').focused);await reuse(v);assert(v.element('trial-book-panel').open);assert(v.element('trial-reuse').focused);assert.equal(v.element('trial-q-1').value,'2');assert.equal(JSON.stringify(v.trial.state),before);await start(v);const item=v.trial.state.items[0],traits=Array.from(item.traits);assert(v.element('trial-book-panel').open);assert.equal(v.trial.state.items[0].status,'inventory');await v.clickTool('menu');await v.click(v.buttons().find(b=>b.dataset.scene==='materials'));await v.clickTool('menu');await v.click(v.buttons().find(b=>b.dataset.scene==='forge'));assert(v.element('trial-book-panel').open);assert.deepEqual(Array.from(v.trial.state.items[0].traits),traits);v.element('trial-book-panel').open=false;await v.change('trial-book','2,0,0,0,0');assert(!v.element('trial-book-panel').open);await v.clickTool('reset');assert(!v.element('trial-book-panel').open);assert.equal(v.trial.state.items.length,0);
});
test('立即武器對照四件同列數據，字級與機率說明保留、沒有排程',async()=>{
 const v=await free();assert.match(v.html(),/lab-weapon-board/);assert.doesNotMatch(v.html(),/排程|開店/);for(const n of [1,2,3,4]){v.element('trial-q-0').value=String(n);await start(v);}const table=v.html().match(/<table class="trial-results weapon-results"[^>]*>([\s\S]*?)<\/table>/)[1];assert.equal((table.match(/<tr>/g)||[]).length,5);assert(!table.includes('<br>'));assert.match(table,/基礎效能／耐久/);assert.match(table,/12／12/);assert.match(table,/8／10/);const css=fs.readFileSync(path.join(__dirname,'../lab.css'),'utf8');assert.match(css,/\.lab-weapon-board\{grid-template-rows:minmax\(0,1fr\)/);assert.match(css,/\.weapon-odds p\{font-size:16px/);assert.match(css,/\.trial-results\{[^}]*font-size:16px/);
});
