'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const T=require('../lab-trial.js'),W=require('../engine.js'),{view,KEY}=require('./ui-harness.cjs');
const mixture=q=>Object.fromEntries(W.MATERIALS.map((m,n)=>[m,q[n]||0]));
async function free(options={}){const v=view({lab:true,autoReview:false,...options});await v.click(v.buttons().find(b=>b.dataset.scene==='forge'));await v.clickTool('forge-trial');return v;}
function fill(v,q){W.MATERIALS.forEach((m,n)=>{v.element('trial-q-'+n).value=String(q[n]||0);});}
const start=v=>v.click(v.buttons().find(b=>b.dataset.trial==='start'));
const names=['木杖','鐵劍','木盾','銅護腕','銀護符','金鈴'];
function noNames(v,except=[]){const output=[v.html(),v.notice(),v.element('trait-descriptions').innerHTML,v.element('trait-tooltip').textContent].join('\n');for(const name of names.filter(n=>!except.includes(n)))assert(!output.includes(name),'unknown name leaked: '+name);}

test('材料與比例決定穩定用途，投入放大增加耐久但不改同配比用途',()=>{
 const cases=[[[2,1,0,0,0],'staff'],[[1,2,0,0,0],'sword'],[[1,1,0,0,0],'shield'],[[1,0,2,0,0],'bracer'],[[0,0,1,2,0],'amulet'],[[0,0,0,1,2],'bell'],[[0,0,1,1,0],'amulet']];
 for(const [q,recipe]of cases){assert.equal(T.measure(mixture(q)).recipe,recipe);assert.equal(T.measure(mixture(q.map(n=>n*2))).recipe,recipe);}
 const x=T.create({random:()=>0});const small=x.start(mixture([1,2]),1,0),large=x.start(mixture([2,4]),1,1);assert.equal(small.recipe,large.recipe);assert.equal(small.maxDurability,11);assert.equal(large.maxDurability,14);assert.equal(large.durability,large.maxDurability);
});
test('零投入／小數／負數／非有限／超界／錯誤材料拒絕且不抽特性、不產物件',()=>{
 let calls=0;const x=T.create({random:()=>{calls++;return 0;}}),before=JSON.stringify(x.state);
 for(const input of [{}, {木頭:0},{木頭:-1},{木頭:1.5},{木頭:NaN},{木頭:Infinity},{木頭:'1'},{木頭:Number.MAX_SAFE_INTEGER},{木頭:21},{木頭:20,鐵:20,銅:1},{木頭:1,其他:1},null,[]]){assert.throws(()=>x.start(input,1,0));assert.equal(JSON.stringify(x.state),before);}
 assert.equal(calls,0);assert.throws(()=>x.start({木頭:1},Number.MAX_SAFE_INTEGER,0),/安全/);assert.equal(calls,0);assert.throws(()=>x.start({木頭:1},1,99),/已處理/);
 const boundary=x.start({木頭:20,鐵:20},1,0);assert.equal(boundary.maxDurability,48);assert.equal(boundary.quality,2);
});
test('242個合法非零組合全部完成，品質效能耐久與特性均有界且不重結算',()=>{
 const recipes=new Set();for(let n=1;n<243;n++){let k=n;const q=W.MATERIALS.map(()=>{const v=k%3;k=Math.floor(k/3);return v;});const x=T.create({random:()=>0.9}),i=x.start(mixture(q),7,0);recipes.add(i.recipe);assert.equal(i.status,'crafting');assert.equal(i.dueMonth,7+W.CRAFT_MONTHS[i.recipe]);assert.equal(x.advance(7).length,0);const result=x.advance(i.dueMonth)[0];assert.equal(result.status,'inventory');assert.equal(result.finishedMonth,i.dueMonth);assert(result.maxDurability>=9&&result.maxDurability<=48);assert(result.quality>=0&&result.quality<=2);assert(Number.isFinite(W.performance(result)));assert.equal(x.advance(i.dueMonth).length,0);assert.equal(x.state.items.length,1);assert.equal(new Set(result.traits).size,result.traits.length);for(const t of result.traits)assert(!W.TRAITS[t].appliesTo||W.TRAITS[t].appliesTo.includes(result.recipe));}
 assert.equal(recipes.size,6);
});
test('同配料可抽出不同實效特性，每件開工固定且揭曉與重複查看不重抽',()=>{
 let values=[0,0,0.9,0.99,0],calls=0;const x=T.create({random:()=>values[calls++]??0}),a=x.start({鐵:1},2,0),b=x.start({鐵:1},2,1);assert.equal(a.recipe,b.recipe);assert.notDeepEqual(a.traits,b.traits);const before=x.state.items.map(i=>i.traits);x.advance(3);x.advance(4);assert.deepEqual(x.state.items.map(i=>i.traits),before);assert.equal(calls,5);const copy=x.state;copy.items[0].traits=[];assert.deepEqual(x.state.items.map(i=>i.traits),before);
 for(const recipe of Object.keys(W.RECIPES)){const base={recipe,quality:1,traits:[],durability:12};assert.equal(W.performance({...base,traits:['light']}),W.performance(base)+1);assert.equal(W.useResult({...base,traits:['solid']}).wear,W.useResult(base).wear-1);if(W.TRAITS.guard.appliesTo.includes(recipe))assert.equal(W.useResult({...base,traits:['guard']}).score,W.useResult(base).score+2);}
});
test('配料簿三態：未發現不列、三份初始未知、完成精確組合變已知與一鍵復用',()=>{
 const x=T.create({random:()=>0});assert.equal(x.state.book.length,3);assert(x.state.book.every(b=>b.name===null));const input={木頭:2,銅:1},m=T.measure(input);assert(!x.state.book.some(b=>b.key===m.key));const i=x.start(input,0,0);assert(!x.state.book.some(b=>b.key===m.key));x.advance(i.dueMonth);assert.equal(x.state.book.length,4);assert.equal(x.state.book.find(b=>b.key===m.key).name,'木杖');const reused=x.reuse(m.key);assert.deepEqual(reused,m.input);reused.木頭=20;assert.equal(x.reuse(m.key).木頭,2);const repeated=x.start(x.reuse(m.key),1,x.state.revision);x.advance(repeated.dueMonth);assert.equal(x.state.book.length,4);const teacher=x.start({銀:1},3,x.state.revision);assert.equal(x.state.book[2].name,null);x.advance(teacher.dueMonth);assert.equal(x.state.book[2].name,'銀護符');assert.equal(x.state.book.length,4);x.reset();assert.equal(x.state.items.length,0);assert.equal(x.state.book.length,3);assert(x.state.book.every(b=>b.name===null));
});
test('真試作頁的未知名稱不在選單、排程、提示、屬性與無障礙說明；兩月物等到完工才揭曉',async()=>{
 const v=await free({trialRandom:()=>0.9});noNames(v);fill(v,[1,0,0,0,0]);await start(v);fill(v,[0,0,0,1,0]);await start(v);noNames(v);assert.equal(v.trial.state.items.length,2);const month=v.state().month;await v.clickAction('open');assert.equal(v.state().month,month+1);assert.equal(v.trial.state.items[0].status,'inventory');assert.equal(v.trial.state.items[1].status,'crafting');noNames(v,['木杖']);await v.clickAction('close');assert.equal(v.state().month,month+1);assert.equal(v.trial.state.items[1].status,'crafting');await v.clickAction('open');assert.equal(v.trial.state.items[1].status,'inventory');assert.match(v.html(),/銀護符/);assert.match(v.html(),/樸實/);assert.match(v.html(),/效能/);assert.match(v.html(),/9／9/);
});
test('試作頁零投入與安全上界提示，不失敗產物、不洩漏成品；同筆過期按鈕不重抽',async()=>{
 let draws=0;const v=await free({trialRandom:()=>{draws++;return 0;}}),before=JSON.stringify(v.trial.state);await start(v);assert.match(v.notice(),/至少1/);assert.equal(JSON.stringify(v.trial.state),before);fill(v,[20,20,1]);await start(v);assert.match(v.notice(),/最多投入40/);assert.equal(JSON.stringify(v.trial.state),before);assert.equal(draws,0);fill(v,[20,20]);const button=v.buttons().find(b=>b.dataset.trial==='start');await v.click(button);assert.equal(v.trial.state.items[0].maxDurability,48);const saved=JSON.stringify(v.trial.state),count=draws;button.disabled=false;await v.click(button);assert.match(v.notice(),/已處理/);assert.equal(JSON.stringify(v.trial.state),saved);assert.equal(draws,count);noNames(v);
});
test('已完工的護身效果不提前列出其他未知成品名稱，同配料的差異可實際對照',async()=>{
 let draws=[0,0.99,0.9,0,0],count=0;const v=await free({trialRandom:()=>draws[count++]??0});fill(v,[0,1]);await start(v);await v.clickAction('open');assert.deepEqual(Array.from(v.trial.state.items[0].traits),['guard']);fill(v,[1,1]);await start(v);noNames(v,['鐵劍']);await v.click(v.trait('guard'));assert.match(v.element('trait-tooltip').textContent,/使用判定＋2/);assert.doesNotMatch(v.element('trait-tooltip').textContent,/木盾|護符|護腕/);fill(v,[0,1]);await start(v);await v.clickAction('close');await v.clickAction('open');const swords=v.trial.state.items.filter(i=>i.recipe==='sword');assert.equal(swords.length,2);assert.notDeepEqual(Array.from(swords[0].traits),Array.from(swords[1].traits));assert.match(v.html(),/最近 3 件試作/);assert.match(v.html(),/護身/);assert.match(v.html(),/輕巧/);assert.match(v.html(),/<td>4／6<\/td>/);assert.match(v.html(),/磨耗 2/);
});
test('表單配料簿套用／完成後復用正常，最近對照可見比例與投入數值差異',async()=>{
 const v=await free({trialRandom:()=>0.5});await v.click(v.buttons().find(b=>b.dataset.trial==='reuse'));assert.equal(v.element('trial-q-0').value,'1');await start(v);await v.clickAction('open');assert.match(v.html(),/木頭1 → 木杖/);assert.match(v.html(),/重用配料/);fill(v,[2,0,0,0,0]);await start(v);await v.clickAction('close');await v.clickAction('open');assert.match(v.html(),/10／10/);assert.match(v.html(),/9／9/);assert.match(v.html(),/最近 2 件試作/);fill(v,[0,2,0,0,0]);await start(v);await v.clickAction('close');await v.clickAction('open');assert.match(v.html(),/鐵劍/);assert.match(v.html(),/木杖/);
});
test('試作重繪、固定模式切換、其他情境與正式存檔隔離，重置只清目前鍛造',async()=>{
 let calls=0;const storage=new Map([[KEY,W.exportSave(W.initialState())],[KEY+'-previous','backup']]),saved=JSON.stringify([...storage]),v=await free({storage,failGet:true,failSet:true,trialRandom:()=>{calls++;return 0.8;}});const forgeBefore=JSON.stringify(v.state());fill(v,[0,0,0,1,0]);await start(v);assert.equal(JSON.stringify(v.state()),forgeBefore);const trialBefore=JSON.stringify(v.trial.state),count=calls;await v.clickTool('forge-fixed');await v.clickTool('forge-trial');assert.equal(JSON.stringify(v.trial.state),trialBefore);await v.change('trial-book','1,0,0,0,0');assert.equal(calls,count);await v.clickTool('menu');await v.click(v.buttons().find(b=>b.dataset.scene==='materials'));await v.clickAction('close');await v.clickAction('open');assert.equal(JSON.stringify(v.trial.state),trialBefore);await v.clickTool('menu');await v.click(v.buttons().find(b=>b.dataset.scene==='forge'));assert.equal(JSON.stringify(v.trial.state),trialBefore);assert.equal(JSON.stringify([...storage]),saved);await v.clickTool('reset');assert.equal(v.trial.state.items.length,0);assert(v.trial.state.book.every(b=>b.name===null));assert.equal(JSON.stringify([...storage]),saved);
});
test('試作仍用真開店且指標轉場不穿透開始試作，導航後隨機記錄保留',async()=>{
 let now=10;const v=await free({now:()=>now,trialRandom:()=>0});fill(v,[1]);await start(v);await v.clickEvent(v.button('open'),{detail:1});const before=JSON.stringify(v.trial.state);assert.equal(await v.clickEvent(v.buttons().find(b=>b.dataset.trial==='start'),{detail:1}),true);assert.equal(JSON.stringify(v.trial.state),before);await v.clickEvent(v.buttons().find(b=>b.dataset.tool==='menu'),{detail:1});await v.clickEvent(v.buttons().find(b=>b.dataset.scene==='forge'),{detail:1});assert.equal(JSON.stringify(v.trial.state),before);now=1000;await start(v);assert.equal(v.trial.state.items.length,2);
});
test('自由配料畫面只有鍛造內容，有限最近4件，主要配料與開工有獨立高度布局',async()=>{
 const v=await free({trialRandom:()=>0});for(let n=0;n<5;n++){fill(v,[1]);await start(v);if(v.state().open)await v.clickAction('close');await v.clickAction('open');}assert.match(v.html(),/最近 4 件試作/);assert.doesNotMatch(v.html(),/NPC|阿岑|小禾|望舒|生活費|欠款|硬幣|技能樹|櫃臺/);assert.equal((v.html().match(/type="number"/g)||[]).length,5);const css=fs.readFileSync(path.join(__dirname,'../lab.css'),'utf8');assert.match(css,/\.trial-fields[^}]*repeat\(3/);assert.match(css,/\.trial-builder[^}]*min-height:0/);assert.match(css,/\.trial-total,\.trial-builder>button\{flex-shrink:0/);assert.match(css,/\.trial-book[^}]*overflow:auto/);
});
