'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),W=require('../engine.js');
const {game,next}=require('./helpers.cjs');
function legacy(version){
 const Old=require(`./fixtures/engine-v${version}.cjs`);
 const g={Old,s:Old.initialState(),act(a){this.s=Old.dispatch(this.s,a).state;},npc(a){const v=Old.activeVisit(this.s);this.act({visitId:v?.id,counterId:v?.counterId,...a});},next(){this.act({type:'close'});this.act({type:'open'});},at(npc){let attempts=0;while(Old.activeVisit(this.s)?.npc!==npc){assert(attempts++<20);const v=Old.activeVisit(this.s);assert(v);this.npc({type:v.phase==='service'?'leave':'decline'});}}};
 g.act({type:'craft',recipe:'staff'});g.act({type:'craft',recipe:'sword'});g.act({type:'open'});g.npc({type:'talk'});for(const itemId of ['item-1','item-2'])g.npc({type:'sell',itemId});
 g.order=(material,quantity,id)=>version===1?g.act({type:'order',material,quantity,requestId:id}):g.npc({type:'order',material,quantity,requestId:id});
 return g;
}
function migrate(g){const current=W.importSave(g.Old.exportSave(g.s));assert.equal(current.coins,g.s.coins);assert.equal(current.debt,g.s.debt);assert.equal(current.month,g.s.month);assert.equal(current.seq,g.s.seq);assert.deepEqual(current.materials,g.s.materials);assert.deepEqual(current.xp,g.s.xp);assert.equal(current.reputation,g.s.reputation);return current;}
function complex(version){
 const g=legacy(version);g.order('木頭',4,'wood');g.order('銅',3,'copper');g.order('銀',2,'silver');g.next();g.at('he');g.npc({type:'talk'});g.act({type:'craft',recipe:'bracer'});const bracer=Object.values(g.s.items).at(-1);g.npc({type:'sell',itemId:bracer.id});g.next();g.at('cen');g.npc({type:'reclaim',itemId:'item-1'});g.act({type:'smelt',itemId:'item-1'});const requested=g.Old.activeVisit(g.s).needs[0];assert(['staff','shield'].includes(requested));g.act({type:'craft',recipe:requested});const inherited=Object.values(g.s.items).at(-1);g.npc({type:'sell',itemId:inherited.id});g.order('金',2,'pending-gold');return {g,bracer:bracer.id,inherited:inherited.id};
}
test('schema1 兩件已售未採購：恢復阿岑等待，金額／ID／交易不重置',()=>{
 const old=legacy(1),s=migrate(old);assert.equal(W.activeVisit(s).npc,'cen');assert.equal(W.activeVisit(s).phase,'service');assert.equal(s.tutorial.ordered,false);assert.equal(s.items['item-1'].owner,'cen');assert.equal(s.items['item-2'].owner,'cen');assert.equal(s.npcs.cen.story,false);for(const id of ['item-1','item-2']){assert.equal(s.items[id].id,id);assert.equal(s.items[id].episodes.length,1);assert.equal(s.items[id].episodes[0].uses,0);assert.equal(s.items[id].history.filter(h=>/買下/.test(h.text)).length,1);}assert.deepEqual(W.importSave(W.exportSave(s)),s);
});
test('schema1 雜務配方／真實使用／固定故事轉換，保留成交金額和歷史次序',()=>{
 const old=legacy(1);old.order('銅',3,'legacy-copper');old.next();old.at('he');old.npc({type:'talk'});old.act({type:'craft',recipe:'watering'});const id=Object.values(old.s.items).at(-1).id;old.npc({type:'sell',itemId:id});old.next();const before=old.s.items[id].history.find(h=>h.text.includes('成交'));const s=migrate(old);assert.equal(s.items[id].recipe,'bracer');assert.equal(s.items[id].history.find(h=>h.text.includes('成交')).text,before.text);assert.deepEqual(s.items[id].history.map(h=>h.month),old.s.items[id].history.map(h=>h.month));assert.equal(s.items[id].episodes[0].uses,1);assert.equal(s.items[id].episodes[0].npc,'he');assert.equal(s.npcs.he.story,false);assert.equal(s.npcs.cen.story,false);assert.equal(s.content.events.length,0);assert.doesNotMatch(JSON.stringify(s),/澆水壺|木凳|銀燈|嫩芽|還書的孩子/);
});
test('schema1 熔鍊來源／傳承／退役持有期與金額完整保留',()=>{
 const old=legacy(1);old.order('木頭',2,'legacy-wood');for(let n=0;n<3;n++)old.next();old.act({type:'reclaim',itemId:'item-1'});old.act({type:'smelt',itemId:'item-1'});old.act({type:'craft',recipe:'stool'});const s=migrate(old),i=Object.values(s.items).at(-1);assert.equal(i.recipe,'shield');assert.equal(i.legacy,'item-1');assert.equal(i.traits.length,2);assert.equal(s.items['item-1'].status,'smelted');assert.equal(s.items['item-1'].episodes[0].until,4);assert.equal(s.items['item-1'].episodes[0].uses,1);assert.equal(s.legacies[0].usedBy,i.id);assert.equal(s.legacies[0].itemId,'item-1');assert.deepEqual(W.importSave(W.exportSave(s)),s);
});
test('schema1 已再售且舊終身使用旗標為真：新持有期仍使用，不重發舊贈還',()=>{
 const old=legacy(1);old.order('銅',1,'legacy');for(let n=0;n<3;n++)old.next();old.act({type:'reclaim',itemId:'item-1'});old.at('cen');old.npc({type:'sell',itemId:'item-1'});assert(old.s.items['item-1'].usedEvent);const g=game();g.s=migrate(old);assert.equal(g.s.items['item-1'].episodes.length,2);assert.equal(g.s.items['item-1'].episodes[1].uses,0);assert.equal(g.s.items['item-1'].durability,9);const original=g.s.items['item-1'].history.slice();next(g);assert.equal(g.s.items['item-1'].episodes[1].uses,1);assert.equal(g.s.items['item-1'].durability,6);assert.equal(g.s.returns.filter(o=>o.itemId==='item-1').length,1);assert.deepEqual(g.s.items['item-1'].history.slice(0,original.length),original);
});
test('schema1 待領贈還仍屬本人，遷移不直接給實物；本人櫃臺才能取得',()=>{
 const old=legacy(1);old.order('木頭',2,'legacy');for(let n=0;n<3;n++)old.next();const g=game();g.s=migrate(old);const offer=g.s.returns.find(o=>o.itemId==='item-1');assert.equal(offer.status,'offered');assert.equal(g.s.items['item-1'].status,'owned');assert.equal(g.s.items['item-1'].durability,3);const current=W.activeVisit(g.s);if(current.npc!=='cen')assert.throws(()=>g.npc({type:'reclaim',itemId:'item-1'}),/只能當面/);while(W.activeVisit(g.s).npc!=='cen')g.npc({type:'decline'});g.npc({type:'reclaim',itemId:'item-1'});assert.equal(g.s.items['item-1'].status,'inventory');assert.equal(g.s.returns.find(o=>o.itemId==='item-1').status,'accepted');
});
for(const version of [2,3])test(`schema${version} 真實複雜檔：成交／使用／熔鍊傳承／待採購／隊列完整保留`,()=>{
 const {g:old,bracer,inherited}=complex(version),s=migrate(old);for(const [id,i]of Object.entries(old.s.items))assert.deepEqual(s.items[id],{...i,dueMonth:null,finishedMonth:i.createdMonth,reservedFor:null});assert.deepEqual(s.orders,old.s.orders);assert.deepEqual(s.returns,old.s.returns);assert.deepEqual(s.legacies,old.s.legacies);assert.equal(s.items[bracer].episodes[0].uses,1);assert.equal(s.items[inherited].owner,'cen');assert.equal(s.items[inherited].legacy,'item-1');assert.equal(s.items['item-1'].status,'smelted');assert.deepEqual(s.visits.map(v=>({id:v.id,status:v.status,phase:v.phase,needs:v.needs,counterId:v.counterId})),old.s.visits.map(v=>({id:v.id,status:v.status,phase:v.phase,needs:v.needs,counterId:v.counterId})));if(version===3)assert.deepEqual(s.content,old.s.content);else assert.equal(s.content.events.length,0);assert.deepEqual(s.npcs,old.s.npcs);const g=game();g.s=W.importSave(W.exportSave(s));const quantity=g.s.materials.金;next(g);assert.equal(g.s.materials.金,quantity+2);assert.equal(g.s.items[inherited].episodes[0].uses,1);next(g);assert.equal(g.s.materials.金,quantity+2);assert.equal(g.s.news.filter(n=>n.id==='delivery-'+s.orders.at(-1).id).length,1);
});
for(const version of [2,3])test(`schema${version} 複雜壞檔：傳承／持有期／人物故事／訂單偽造拒絕`,()=>{
 const {g:old}=complex(version);for(const mutate of [s=>s.legacies[0].usedBy='missing',s=>s.items['item-1'].episodes[0].npc='he',s=>s.orders.push(s.orders[0]),s=>{s.npcs.shu.story=true;s.npcs.shu.storyItem='item-1';},s=>s.items['item-2'].owner='fake']){const d=JSON.parse(old.Old.exportSave(old.s));mutate(d.state);assert.throws(()=>W.importSave(JSON.stringify(d)),/存檔/);}
});
module.exports={legacy,complex};

test('schema1 銀燈成交與後續真實使用映射護符，保留原金額及持有期',()=>{
 const old=legacy(1);old.order('銅',1,'copper');old.order('銀',1,'silver');old.next();old.at('he');old.npc({type:'talk'});old.act({type:'craft',recipe:'watering'});old.npc({type:'sell',itemId:Object.values(old.s.items).at(-1).id});old.act({type:'craft',recipe:'lamp'});const id=Object.values(old.s.items).at(-1).id;old.next();old.at('shu');old.npc({type:'talk'});old.npc({type:'sell',itemId:id});assert.equal(old.s.items[id].owner,'shu');old.next();const s=migrate(old),i=s.items[id];assert.equal(i.recipe,'amulet');assert.equal(i.owner,'shu');assert.deepEqual(i.history.map(h=>h.month),old.s.items[id].history.map(h=>h.month));assert.equal(i.history[1].text,old.s.items[id].history[1].text);assert.match(i.history[2].text,/已留下使用紀錄.*佩戴護身.*舊版紀錄/);assert.doesNotMatch(i.history[2].text,/圖書室|安心讀書/);assert.equal(i.episodes[0].npc,'shu');assert.equal(i.episodes[0].uses,1);assert.equal(i.dueMonth,null);assert.equal(s.content.events.length,0);assert.deepEqual(W.importSave(W.exportSave(s)),s);
});
