'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),W=require('../engine.js');
const {view}=require('./ui-harness.cjs'),{game,ready,craft,next,at}=require('./helpers.cjs'),{twoMonthCustomer}=require('./regression-helpers.cjs');
function screen(v){assert.match(v.html(),/aria-label="月結逐筆閱覽"/);assert.doesNotMatch(v.html(),/aria-label="目前顧客"|data-tab=|data-action="[^\"]+&quot;sell&quot;|id="door"/);assert.equal((v.html().match(/class="review-card"/g)||[]).length,1);}
test('真正UI單件逐卡：先生活費再完整作品，結算期間沒有交易入口',async()=>{
 const v=view({raw:null,autoReview:false});await v.clickAction('craft',{recipe:'staff'});await v.clickAction('open');screen(v);assert.match(v.html(),/收支結算|現金扣除 8 枚/);assert.doesNotMatch(v.html(),/完工報告|效能|耐久/);assert.equal(v.state().coins,12);await v.clickAction('review-next');screen(v);assert.match(v.html(),/木杖 · 樸實/);assert.match(v.html(),/效能<\/dt><dd>3/);assert.match(v.html(),/耐久<\/dt><dd>9／9/);assert.match(v.html(),/輕巧|沒有預訂/);assert.match(v.html(),/尚未鑑定/);assert.equal(v.state().items['item-1'].appraised,false);assert.equal(v.state().xp.appraisal,0);await v.clickAction('review-next');assert.doesNotMatch(v.html(),/月結逐筆閱覽/);assert.match(v.html(),/目前顧客/);assert.equal(v.state().coins,12);assert.equal(v.state().xp.craft,1);
});
test('多件逐卡及重載：不一次塞滿、相同按鈕和複本不跳下一件',async()=>{
 const v=view({raw:null,autoReview:false});for(const recipe of ['staff','sword','staff'])await v.clickAction('craft',{recipe});await v.clickAction('open');const b=v.button('review-next'),copy={dataset:{...b.dataset},disabled:false};await v.click(b);const saved=v.raw();await v.click(b);await v.click(copy);assert.equal(v.raw(),saved);assert.equal(v.state().monthReview.cursor,1);assert.match(v.html(),/木杖 · 樸實/);assert.doesNotMatch(v.html(),/鐵劍 · 樸實/);const reload=view({raw:saved,autoReview:false});screen(reload);assert.equal(reload.state().month,1);assert.equal(reload.state().coins,12);await reload.clickAction('review-next');assert.match(reload.html(),/鐵劍 · 樸實/);assert.doesNotMatch(reload.html(),/木杖 · 樸實/);await reload.clickAction('review-next');assert.match(reload.html(),/作品 3／3/);const last=reload.button('review-next'),old={dataset:{...last.dataset},disabled:false};await reload.click(last);const done=reload.raw();await reload.click(old);assert.equal(reload.raw(),done);assert.equal(reload.state().month,1);assert.equal(reload.state().xp.craft,3);
});
test('自然欠款月份UI：現金四與欠款四分開，全欠八不當現金扣八',async()=>{
 const g=game();g.do({type:'open'});g.do({type:'close'});g.do({type:'open'});const v=view({state:g.s,autoReview:false});await v.clickAction('close');await v.clickAction('open');screen(v);assert.match(v.html(),/現金扣除 4 枚；不足的 4 枚記為新增欠款/);await v.clickAction('review-next');await v.clickAction('close');await v.clickAction('open');assert.match(v.html(),/現金扣除 0 枚；不足的 8 枚記為新增欠款/);assert.equal(v.state().debt,12);
});
test('兩月預訂UI：尚未完成只有費用，完工詳情指出本人且不提早付款',async()=>{
 const g=twoMonthCustomer(),c=g.s.commissions.at(-1),v=view({state:g.s,autoReview:false});await v.clickAction('close');await v.clickAction('open');screen(v);assert.equal(v.state().items[c.itemId].status,'crafting');assert.equal(v.state().monthReview.entries.length,1);assert.doesNotMatch(v.html(),/完工報告|效能/);await v.clickAction('review-next');await v.clickAction('close');await v.clickAction('open');const balance=v.state().coins,debt=v.state().debt;await v.clickAction('review-next');screen(v);assert.match(v.html(),/銀護符 · 細緻/);assert.match(v.html(),/效能<\/dt><dd>10/);assert.match(v.html(),/護身/);assert.match(v.html(),/保留給望舒，當面交貨才付款/);assert.equal(v.state().items[c.itemId].owner,null);assert.equal(v.state().items[c.itemId].appraised,false);assert.equal(v.state().xp.appraisal,0);await v.clickAction('review-next');assert.equal(v.state().coins,balance);assert.equal(v.state().debt,debt);assert.equal(v.state().commissions.at(-1).status,'ready');
});
test('鑑定選用文案及實際用途：看完報告仍可鑑定一次並直接交貨',async()=>{
 const g=ready();g.npc({type:'talk'});g.npc({type:'accept-commission',requestId:'ui-report-appraisal'});const c=g.s.commissions.at(-1),v=view({state:g.s,autoReview:false});await v.clickAction('close');await v.clickAction('open');await v.clickAction('review-next');assert.match(v.html(),/尚未鑑定/);await v.clickAction('review-next');while(W.activeVisit(v.state())?.npc!=='he'){const p=W.activeVisit(v.state());await v.clickAction(p.phase==='service'?'leave':'decline');}assert.match(v.html(),/可先鑑定.*也能直接推薦或交付/);assert.doesNotMatch(v.html(),/鑑定這件物品，再向她推薦/);await v.clickTab('inventory');assert(v.button('appraise',{itemId:c.itemId}));await v.clickAction('appraise',{itemId:c.itemId});assert.equal(v.state().xp.appraisal,1);assert.equal(v.state().items[c.itemId].appraised,true);assert.match(v.html(),/銅第 3 階.*效能 6.*耐久 9／9/);assert(v.button('appraise',{itemId:c.itemId}).disabled);await v.clickAction('deliver',{itemId:c.itemId});assert.equal(v.state().commissions.at(-1).status,'delivered');
});
test('無鑑定仍可直接交貨，沒有完工不造零件／零收入卡',async()=>{
 const g=ready();g.npc({type:'talk'});g.npc({type:'accept-commission',requestId:'ui-no-appraise'});const c=g.s.commissions.at(-1),v=view({state:g.s,autoReview:false});await v.clickAction('close');await v.clickAction('open');await v.clickAction('review-next');await v.clickAction('review-next');while(W.activeVisit(v.state())?.npc!=='he'){const p=W.activeVisit(v.state());await v.clickAction(p.phase==='service'?'leave':'decline');}await v.clickAction('deliver');assert.equal(v.state().items[c.itemId].appraised,false);assert.equal(v.state().xp.appraisal,0);const empty=view({raw:null,autoReview:false});await empty.clickAction('open');assert.equal(empty.state().monthReview.entries.length,1);assert.doesNotMatch(empty.html(),/完工報告|沒有完工|收入 0|作品 0/);assert.match(empty.html(),/閱完了，開始接客/);await empty.clickAction('review-next');assert.match(empty.html(),/目前顧客/);
});
