'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),W=require('../engine.js');
const {view}=require('./ui-harness.cjs'),{game,intro}=require('./helpers.cjs'),{personalRoute}=require('./personal-helpers.cjs');
const panel=v=>v.html().split('id="panel"')[1],cards=v=>[...panel(v).matchAll(/<article class="person">([\s\S]*?)<\/article>/g)].map(m=>m[1]),card=(v,name)=>cards(v).find(s=>s.includes(`<span class="person-name">${name} `));
test('真正首次接待立即顯人物頁，只列阿岑，關店重載仍可看而無虛構經歷',async()=>{
 const v=view({raw:null,autoReview:false});assert(!v.buttons().some(b=>b.dataset.tab==='people'));await v.clickAction('open');assert(!v.buttons().some(b=>b.dataset.tab==='people'));await v.clickAction('review-next');await v.clickTab('people');assert.equal(cards(v).length,1);assert.match(card(v,'阿岑'),/等級 1 · 行路 0/);assert.match(panel(v),/每種新的可靠經歷增加1點能力/);assert.match(card(v,'阿岑'),/行路達2/);assert.match(card(v,'阿岑'),/尚未留下實際行動經歷/);assert.doesNotMatch(panel(v),/小禾|望舒|舊驛道|已完成）/);await v.clickAction('close');const reload=view({raw:v.raw()});await reload.clickTab('people');assert.equal(cards(reload).length,1);assert.match(card(reload,'阿岑'),/行路 0/);
});
test('親驗缺口回歸：不派遣送客換月照常新客，人物鳥信可看，沒有假交付',async()=>{
 const g=game();intro(g);const v=view({state:g.s});await v.clickAction('leave');await v.clickAction('close');await v.clickAction('open');assert.equal(W.activeVisit(v.state()).npc,'he');assert.equal(v.state().tutorial.ordered,false);assert.equal(v.state().tutorial.delivered,false);assert.doesNotMatch(v.html(),/兩件武器都收好了/);await v.clickTab('people');assert.equal(cards(v).length,2);assert(card(v,'阿岑'));assert(card(v,'小禾'));assert(!card(v,'望舒'));assert.match(card(v,'小禾'),/等級 1 · 辨路 0/);await v.clickTab('mail');assert.match(panel(v),/阿岑.*使用|夜路回音/);assert.equal(v.state().tutorial.delivered,false);await v.clickAction('talk');assert(W.canAppraise(v.state()));
});
test('三人一致顯示等級能力、真實經歷、目標與持有詳情，不曝光完整條件表',async()=>{
 const r=personalRoute(),v=view({state:r.state});await v.clickTab('people');assert.equal(cards(v).length,3);for(const [name,ability] of [['阿岑','行路'],['小禾','辨路'],['望舒','感知']]){const c=card(v,name);assert.match(c,new RegExp(`等級 2 · ${ability} 3`));assert.match(c,/已完成經歷/);assert.match(c,/目前目標/);assert.match(c,/（已完成）/);assert.match(c,/持有裝備/);assert.match(panel(v),/每種新的可靠經歷|重複買賣、同類使用或空過月不增加/);}assert.match(card(v,'阿岑'),/舊杖新路（紀錄，不重複加能力）/);assert.match(card(v,'小禾'),/接縫再試（紀錄，不重複加能力）/);assert.doesNotMatch(panel(v),/minQuality|score|episodeId|roadMonth|效能≥|耐久≥|完整觸發/);
});
test('望舒缺裝備目標給可行提示與當前持有數值，未完成不宣稱可採集',async()=>{
 const r=personalRoute(),v=view({state:r.seed});await v.clickTab('people');const c=card(v,'望舒');assert.match(c,/目前目標：驛道警示/);assert.doesNotMatch(c,/目前目標[^<]+已完成/);assert.match(c,/細緻以上.*護身.*護符/);assert.match(c,/護符和鈴要一起帶上路.*並行準備.*堅固傳承/);for(const i of W.owned(r.seed,'shu'))assert(c.includes(`效能 ${W.performance(i)} · 耐久 ${i.durability}／${i.maxDurability}`));
});
test('剛交貨不能提前宣稱個人完成；月結照常依序看完才可用新採集',async()=>{
 const r=personalRoute(),v=view({state:r.before,autoReview:false});await v.clickTab('people');assert.doesNotMatch(card(v,'望舒'),/目前目標[^<]+已完成/);await v.clickTab('purchase');assert(!v.buttons().some(b=>b.action?.type==='gather-route-form'));await v.clickAction('close');await v.clickAction('open');assert(W.characterProgress(v.state(),'shu').completed);assert.match(v.html(),/收支結算/);assert(!v.buttons().some(b=>b.dataset.tab==='people'));assert(!v.buttons().some(b=>b.action?.type==='gather-route-form'));await v.reviewAll();while(W.activeVisit(v.state())?.npc!=='shu'){const p=W.activeVisit(v.state());await v.clickAction(p.phase==='service'?'leave':'decline');}await v.clickTab('people');assert.match(card(v,'望舒'),/目前目標：驛道警示（已完成）/);await v.clickTab('purchase');assert(v.button('gather-route-form'));assert.match(panel(v),/下月帶回.*3 個/);
});
test('完成目標後阿岑與望舒的真正採集表單可用，扣款去重並收起入口',async()=>{
 const r=personalRoute();for(const npc of ['cen','shu']){const v=view({state:r.state});while(W.activeVisit(v.state())?.npc!==npc){const p=W.activeVisit(v.state());await v.clickAction(p.phase==='service'?'leave':'decline');}if(W.activeVisit(v.state()).phase==='request'){const choice=W.inventory(v.state()).find(i=>W.suitable(v.state(),i));if(choice)await v.clickAction('sell',{itemId:choice.id});else{await v.clickAction('accept-commission');const c=v.state().commissions.at(-1);while(v.state().items[c.itemId].status==='crafting'){await v.clickAction('close');await v.clickAction('open');}while(W.activeVisit(v.state())?.npc!==npc){const p=W.activeVisit(v.state());await v.clickAction(p.phase==='service'?'leave':'decline');}await v.clickAction('deliver');}}await v.clickTab('purchase');v.element('order-material').value='木頭';const b=v.button('gather-route-form'),net=v.state().coins-v.state().debt;await v.click(b);assert.equal(v.state().coins-v.state().debt,net-6);assert.equal(v.state().journey.outings.at(-1).npc,npc);assert(!v.buttons().some(b=>b.action?.type==='gather-route-form'));assert.match(panel(v),/材料委託已交代/);const raw=v.raw();await v.click(b);assert.equal(v.raw(),raw);}
});
