'use strict';
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const root = path.resolve(__dirname, '..');
for (const file of ['content.js', 'engine.js', 'trait-tips.js', 'app.js', 'lab-core.js', 'lab-scenarios.js', 'lab.js', 'server.cjs']) execFileSync(process.execPath, ['--check', path.join(root, file)], { stdio: 'inherit', windowsHide: true });
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
if (!html.includes('lang="zh-Hant"')) throw new Error('缺少正體中文語言設定');
for (const file of ['style.css', 'content.js', 'engine.js', 'trait-tips.js', 'app.js', 'SPEC.md']) if (!fs.existsSync(path.join(root, file))) throw new Error(`缺少 ${file}`);
for(const file of ['lab.html','lab.css','lab-core.js','lab-scenarios.js','lab.js']) if(!fs.existsSync(path.join(root,file)))throw new Error(`缺少 ${file}`);
if(!fs.readFileSync(path.join(root,'lab.html'),'utf8').includes('lang="zh-Hant"'))throw new Error('測試頁缺少正體中文設定');
const W=require('../engine.js');for(const scene of Object.values(require('../lab-scenarios.js')))W.validate(scene.state);
const info = require('./stamp-build.cjs');
console.log(`建置驗證完成 ${info.version}，${info.builtAt}。純靜態程式無需套件安裝。`);
