'use strict';
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const root = path.resolve(__dirname, '..');
for (const file of ['engine.js', 'app.js', 'server.cjs']) execFileSync(process.execPath, ['--check', path.join(root, file)], { stdio: 'inherit', windowsHide: true });
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
if (!html.includes('lang="zh-Hant"')) throw new Error('缺少正體中文語言設定');
for (const file of ['style.css', 'engine.js', 'app.js', 'SPEC.md']) if (!fs.existsSync(path.join(root, file))) throw new Error(`缺少 ${file}`);
const info = require('./stamp-build.cjs');
console.log(`建置驗證完成 ${info.version}，${info.builtAt}。純靜態程式無需套件安裝。`);
